// ===========================
// VetShift — Mock Data
// For development & demo purposes
// ===========================

import type {
    Clinic, Veterinarian, Shift, Review,
    WalletTransaction, WalletBalance, ShiftApplication
} from './types';

// === Clinics ===
export const mockClinics: Clinic[] = [
    {
        id: 'clinic-1',
        user_id: 'user-clinic-1',
        name: 'Centervet Salvador',
        cnpj: '12.345.678/0001-00',
        logo_url: null,
        address: 'Rua das Hortênsias, 123 - Pituba',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9822,
        longitude: -38.4513,
        phone: '(71) 3333-1234',
        is_24h: true,
        rating: 4.8,
        total_reviews: 42,
        total_shifts: 156,
        created_at: '2025-06-15T10:00:00Z',
    },
    {
        id: 'clinic-2',
        user_id: 'user-clinic-2',
        name: 'Pet Master Pituba',
        cnpj: '98.765.432/0001-00',
        logo_url: null,
        address: 'Av. Paulo VI, 456 - Pituba',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9780,
        longitude: -38.4530,
        phone: '(71) 3333-5678',
        is_24h: true,
        rating: 4.6,
        total_reviews: 31,
        total_shifts: 98,
        created_at: '2025-07-20T10:00:00Z',
    },
    {
        id: 'clinic-3',
        user_id: 'user-clinic-3',
        name: 'Latidos e Miados',
        cnpj: '56.789.012/0001-00',
        logo_url: null,
        address: 'Rua Waldemar Falcão, 789 - Brotas',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9900,
        longitude: -38.4800,
        phone: '(71) 3333-9012',
        is_24h: false,
        rating: 4.9,
        total_reviews: 63,
        total_shifts: 45,
        created_at: '2025-08-10T10:00:00Z',
    },
    {
        id: 'clinic-4',
        user_id: 'user-clinic-4',
        name: 'VetService Costa Azul',
        cnpj: '34.567.890/0001-00',
        logo_url: null,
        address: 'Rua Osvaldo Cruz, 321 - Costa Azul',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9850,
        longitude: -38.4450,
        phone: '(71) 3333-3456',
        is_24h: false,
        rating: 4.5,
        total_reviews: 18,
        total_shifts: 32,
        created_at: '2025-09-01T10:00:00Z',
    },
];

// === Veterinarians ===
export const mockVets: Veterinarian[] = [
    {
        id: 'vet-1',
        user_id: 'user-vet-1',
        name: 'Dr. Lucas Martins',
        crmv: '12345',
        crmv_state: 'BA',
        crmv_verified: true,
        crmv_document_url: null,
        avatar_url: null,
        specialties: ['clinica_geral', 'emergencia', 'cirurgia'],
        bio: 'Veterinário com 8 anos de experiência em clínica de pequenos animais e emergências. Apaixonado por cirurgia e atendimento de urgência.',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9714,
        longitude: -38.5124,
        radius_km: 15,
        is_available: true,
        rating: 4.9,
        total_reviews: 127,
        total_shifts: 238,
        completion_rate: 98,
        created_at: '2025-05-10T10:00:00Z',
    },
    {
        id: 'vet-2',
        user_id: 'user-vet-2',
        name: 'Dra. Camila Souza',
        crmv: '67890',
        crmv_state: 'BA',
        crmv_verified: true,
        crmv_document_url: null,
        avatar_url: null,
        specialties: ['dermatologia', 'clinica_geral'],
        bio: 'Especialista em dermatologia veterinária. Pós-graduada pela UFBA com foco em alergias e doenças de pele.',
        city: 'Salvador',
        state: 'BA',
        latitude: -12.9900,
        longitude: -38.4600,
        radius_km: 20,
        is_available: true,
        rating: 4.7,
        total_reviews: 83,
        total_shifts: 142,
        completion_rate: 96,
        created_at: '2025-06-01T10:00:00Z',
    },
    {
        id: 'vet-3',
        user_id: 'user-vet-3',
        name: 'Dr. Rafael Oliveira',
        crmv: '11223',
        crmv_state: 'BA',
        crmv_verified: true,
        crmv_document_url: null,
        avatar_url: null,
        specialties: ['ortopedia', 'cirurgia'],
        bio: 'Ortopedista veterinário com especialização em fraturas e cirurgias articulares em cães e gatos.',
        city: 'Salvador',
        state: 'BA',
        latitude: -13.0050,
        longitude: -38.5100,
        radius_km: 10,
        is_available: false,
        rating: 4.8,
        total_reviews: 45,
        total_shifts: 89,
        completion_rate: 99,
        created_at: '2025-07-15T10:00:00Z',
    },
];

// === Shifts ===
export const mockShifts: Shift[] = [
    {
        id: 'shift-1',
        clinic_id: 'clinic-1',
        clinic: mockClinics[0],
        specialty: 'clinica_geral',
        date: '2026-03-03',
        start_time: '19:00',
        end_time: '07:00',
        duration_hours: 12,
        value: 200,
        description: 'Plantão noturno em clínica 24h. Atendimento de pequenos animais. Equipe de enfermagem presente no local.',
        requirements: ['Experiência com emergências', 'CRMV ativo'],
        accept_proposals: true,
        status: 'open',
        assigned_vet_id: null,
        applicant_count: 3,
        created_at: '2026-03-01T14:30:00Z',
    },
    {
        id: 'shift-2',
        clinic_id: 'clinic-2',
        clinic: mockClinics[1],
        specialty: 'emergencia',
        date: '2026-03-03',
        start_time: '19:00',
        end_time: '07:00',
        duration_hours: 12,
        value: 280,
        description: 'Plantão de emergência noturno. Necessário experiência com atendimento de urgência e estabilização.',
        requirements: ['Experiência com emergências', 'CRMV ativo', 'Mínimo 3 anos de experiência'],
        accept_proposals: false,
        status: 'open',
        assigned_vet_id: null,
        applicant_count: 1,
        created_at: '2026-03-01T16:00:00Z',
    },
    {
        id: 'shift-3',
        clinic_id: 'clinic-3',
        clinic: mockClinics[2],
        specialty: 'dermatologia',
        date: '2026-03-04',
        start_time: '08:00',
        end_time: '18:00',
        duration_hours: 10,
        value: 300,
        description: 'Atendimento dermatológico agendado. 8 consultas pré-agendadas + demanda espontânea.',
        requirements: ['Especialização em dermatologia', 'CRMV ativo'],
        accept_proposals: true,
        status: 'open',
        assigned_vet_id: null,
        applicant_count: 0,
        created_at: '2026-03-02T09:00:00Z',
    },
    {
        id: 'shift-4',
        clinic_id: 'clinic-1',
        clinic: mockClinics[0],
        specialty: 'clinica_geral',
        date: '2026-03-03',
        start_time: '07:00',
        end_time: '19:00',
        duration_hours: 12,
        value: 180,
        description: 'Plantão diurno. Consultas agendadas e demanda espontânea. Clínica de pequenos animais.',
        requirements: ['CRMV ativo'],
        accept_proposals: true,
        status: 'confirmed',
        assigned_vet_id: 'vet-1',
        assigned_vet: mockVets[0],
        applicant_count: 2,
        created_at: '2026-02-28T10:00:00Z',
    },
    {
        id: 'shift-5',
        clinic_id: 'clinic-4',
        clinic: mockClinics[3],
        specialty: 'cirurgia',
        date: '2026-03-05',
        start_time: '08:00',
        end_time: '14:00',
        duration_hours: 6,
        value: 350,
        description: 'Cirurgias eletivas agendadas: 2 castrações e 1 mastectomia. Equipe de apoio disponível.',
        requirements: ['Experiência cirúrgica', 'CRMV ativo', 'Mínimo 5 anos de experiência'],
        accept_proposals: false,
        status: 'open',
        assigned_vet_id: null,
        applicant_count: 2,
        created_at: '2026-03-02T11:00:00Z',
    },
];

// === Reviews ===
export const mockReviews: Review[] = [
    {
        id: 'review-1',
        shift_id: 'shift-old-1',
        reviewer_id: 'clinic-1',
        reviewer_name: 'Centervet Salvador',
        reviewer_role: 'clinic',
        target_id: 'vet-1',
        rating: 5,
        comment: 'Excelente profissional! Pontual, atencioso e muito competente. Recomendo fortemente.',
        created_at: '2026-02-20T08:00:00Z',
    },
    {
        id: 'review-2',
        shift_id: 'shift-old-2',
        reviewer_id: 'clinic-2',
        reviewer_name: 'Pet Master Pituba',
        reviewer_role: 'clinic',
        target_id: 'vet-1',
        rating: 5,
        comment: 'Dr. Lucas é um dos melhores plantonistas que já tivemos. Muito dedicado e responsável.',
        created_at: '2026-02-15T10:00:00Z',
    },
    {
        id: 'review-3',
        shift_id: 'shift-old-3',
        reviewer_id: 'clinic-3',
        reviewer_name: 'Latidos e Miados',
        reviewer_role: 'clinic',
        target_id: 'vet-1',
        rating: 4,
        comment: 'Bom atendimento, resolveu todos os casos com agilidade. Voltaria a chamar.',
        created_at: '2026-02-10T14:00:00Z',
    },
];

// === Wallet Transactions ===
export const mockTransactions: WalletTransaction[] = [
    {
        id: 'tx-1',
        user_id: 'user-vet-1',
        type: 'credit',
        amount: 200,
        description: 'Plantão - Centervet Salvador',
        reference_id: 'shift-old-1',
        status: 'completed',
        created_at: '2026-03-02T08:00:00Z',
    },
    {
        id: 'tx-2',
        user_id: 'user-vet-1',
        type: 'credit',
        amount: 250,
        description: 'Plantão - Pet Master Pituba',
        reference_id: 'shift-old-2',
        status: 'completed',
        created_at: '2026-02-28T07:30:00Z',
    },
    {
        id: 'tx-3',
        user_id: 'user-vet-1',
        type: 'withdrawal',
        amount: 500,
        description: 'Saque via TED',
        reference_id: null,
        status: 'completed',
        created_at: '2026-02-25T14:00:00Z',
    },
    {
        id: 'tx-4',
        user_id: 'user-vet-1',
        type: 'credit',
        amount: 180,
        description: 'Plantão - Latidos e Miados',
        reference_id: 'shift-old-3',
        status: 'completed',
        created_at: '2026-02-22T07:00:00Z',
    },
    {
        id: 'tx-5',
        user_id: 'user-vet-1',
        type: 'credit',
        amount: 350,
        description: 'Plantão - VetService Costa Azul',
        reference_id: 'shift-old-4',
        status: 'pending',
        created_at: '2026-03-02T19:00:00Z',
    },
];

export const mockWalletBalance: WalletBalance = {
    available: 1450,
    pending: 400,
};

// === Shift Applications ===
export const mockApplications: ShiftApplication[] = [
    {
        id: 'app-1',
        shift_id: 'shift-1',
        vet_id: 'vet-1',
        vet: mockVets[0],
        proposed_value: null,
        message: 'Tenho disponibilidade e experiência com plantões noturnos. Posso estar aí às 18:45.',
        status: 'pending',
        created_at: '2026-03-01T18:00:00Z',
    },
    {
        id: 'app-2',
        shift_id: 'shift-1',
        vet_id: 'vet-2',
        vet: mockVets[1],
        proposed_value: 220,
        message: 'Disponível para o plantão. Experiência de 6 anos com emergências.',
        status: 'pending',
        created_at: '2026-03-01T19:30:00Z',
    },
];
